version: '3'

services:
  slack:
    build:
      context: ./
      dockerfile: ./slack/Dockerfile
    env_file:
      - .env.default
      - .env.overrides
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - 5432:15432
    environment:
      - POSTGRES_PASSWORD=henk
      - POSTGRES_DB=karmabot

  